package model.temporalView.enums;

public enum TemporalViewOperator {
	
	ADD_TEMPORAL_CHAIN,
	REMOVE_TEMPORAL_CHAIN,
	
	ADD_TEMPORAL_CHAIN_MEDIA,
	ADD_SYNC_RELATION, SET_MASTER_MEDIA, 
	CLEAR_TEMPORAL_CHAIN_LIST;
	
}
