package model.temporalView.enums;

public enum TemporalViewOperator {
	
	ADD_TEMPORAL_CHAIN,
	REMOVE_TEMPORAL_CHAIN,
	
	SET_MASTER_MEDIA,
	ADD_TEMPORAL_CHAIN_MEDIA,
	REMOVE_TEMPORAL_CHAIN_MEDIA,
	CLEAR_SELECTION_TEMPORAL_MEDIA,
	SELECT_TEMPORAL_MEDIA,
	ADD_SYNC_RELATION,
	ADD_INTERACTIVITY_RELATION,
	REMOVE_SYNC_RELATION,
	REMOVE_SLAVE_NODE_OF_SYNC_RELATION,
	CLEAR_TEMPORAL_CHAIN_LIST, 
	REMOVE_INTERACTIVITY_RELATION, 
	EDIT_INTERACTIVITY_RELATION;
	
}
