package model.temporalView.enums;

public enum TemporalViewOperator {
	
	ADD_TEMPORAL_CHAIN,
	REMOVE_TEMPORAL_CHAIN,
	
	SET_MASTER_MEDIA,
	ADD_TEMPORAL_CHAIN_MEDIA,
	REMOVE_TEMPORAL_CHAIN_MEDIA,
	ADD_SYNC_RELATION,
	CLEAR_TEMPORAL_CHAIN_LIST;
	
}
